// Generated by gencpp from file odometry/Encoder.msg
// DO NOT EDIT!


#ifndef ODOMETRY_MESSAGE_ENCODER_H
#define ODOMETRY_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace odometry
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , left_enc(0)
    , right_enc(0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_enc(0)
    , right_enc(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _left_enc_type;
  _left_enc_type left_enc;

   typedef uint32_t _right_enc_type;
  _right_enc_type right_enc;




  typedef boost::shared_ptr< ::odometry::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometry::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::odometry::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::odometry::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::odometry::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometry::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometry::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odometry

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'odometry': ['/home/oshadha/hsa2/catkin_ws/src/odometry/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odometry::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometry::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometry::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e67c8e7afd2165bbd822f101a08e981";
  }

  static const char* value(const ::odometry::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e67c8e7afd2165bULL;
  static const uint64_t static_value2 = 0xbd822f101a08e981ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometry::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometry/Encoder";
  }

  static const char* value(const ::odometry::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometry::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 left_enc\n\
uint32 right_enc\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::odometry::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometry::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_enc);
      stream.next(m.right_enc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometry::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometry::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_enc: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.left_enc);
    s << indent << "right_enc: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.right_enc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETRY_MESSAGE_ENCODER_H
